vip_box = [{'free_places': 0},
           {'name': 'Alex',
            'surname': 'Sanders',
            'number_place': 1,
            'vip_place': 'true'},
           {'name': 'Andy',
            'surname': 'Ruis',
            'place': 2,
            'vip_place': 'true'},
           {'name': 'Tony',
            'surname': 'Montana',
            'place': 3,
            'vip_place': 'true'},
           {'name': 'Iggy',
            'surname': 'Azelia',
            'place': 4,
            'vip_place': 'true'},
           {'name': 'Oleksandr',
            'surname': 'Usyk',
            'place': 5,
            'vip_place': 'true'}]
common_room = [{'free_places': 22},
               {'name': 'Killian',
                'surname': 'Merphy',
                'number_place': 1,
                'vip_place': 'false'},
               {'name': 'Andy',
                'surname': 'Couture',
                'place': 2,
                'vip_place': 'false'},
               {'name': 'Tony',
                'surname': 'Ferguson',
                'place': 3,
                'vip_place': 'false'},
               {'name': 'Kamaru',
                'surname': 'Usman',
                'place': 4,
                'vip_place': 'false'},
               {'name': 'Colby',
                'surname': 'Covington',
                'place': 5,
                'vip_place': 'false'}]
print(f"Guests in vip box: {vip_box}. \n "
      f"Guests in common room: {common_room}.")
